03 add navigation pokemons infos
WildCodeSchool/2103-lille-js-p2-g4-pokemon pull request #17
Opened 2021-05-04 10:20 UTC by Zamomako

2021-05-04 11:13 UTC, AntoineCAU approved these changes, later dismissed
Perfect, i understand everything.
Good feature

2021-05-05 07:15 UTC, LoicBrassart requested changes
Edge cases to fix

2021-05-05 07:15 UTC, LoicBrassart commented on src/components/PokemonPage.jsx
> +    history.push(`/id/${infos.id - 1}`);
Beware of edge cases: what happens if I'm on Bulbasaur (#1) ? Or on the last one ?

2021-05-05 09:18 UTC, AntoineCAU approved these changes, later dismissed
Perfect Robin, nice fix

2021-05-05 10:10 UTC, LoicBrassart submitted a review, later dismissed
Much better !

2021-05-05 10:12 UTC, AntoineCAU approved these changes, later dismissed

2021-05-05 11:19 UTC, LoicBrassart approved these changes
No more Evil

2021-05-05 11:45 UTC, AntoineCAU approved these changes

2021-05-05 11:45 UTC, merged