02 creation pokemon infos
WildCodeSchool/2103-lille-js-p2-g4-pokemon pull request #7
Opened 2021-04-22 11:44 UTC by AntoineCAU

2021-04-22 11:46 UTC, Gasparddhi submitted a review, later dismissed
Changing the structure to a router okay

2021-04-22 13:56 UTC, LoicBrassart commented
Require a validation from your SM before you assign me plz ^^

2021-04-22 13:58 UTC, Gasparddhi approved these changes, later dismissed
Everything is ok for me

2021-04-22 14:09 UTC, LoicBrassart requested changes
No, no, nonono ! >_<

2021-04-22 14:09 UTC, LoicBrassart commented on src/components/PokemonPage.jsx
> +          name: 'Fatalfoutre',
NOEZ ! （╯°□°）╯︵( .o.)

2021-04-22 14:09 UTC, LoicBrassart commented on src/components/PokemonPage.jsx
> +        `https://pokeapi.co/api/v2/pokemon/${props.match.params.pokemonName}`
You should use hooks (`useParams()` from `react-router-dom`)

2021-04-23 07:04 UTC, Gasparddhi approved these changes
Code très propre j'approuve très beau travail bravo !

2021-04-23 07:04 UTC, Gasparddhi approved these changes
well done

2021-04-28 06:27 UTC, LoicBrassart approved these changes
No more Evil

2021-04-28 06:55 UTC, merged